# Workflow starts automatically on push or can be triggered manually.
# This is a desirable pattern as it allows for adhoc test runs without a code push
name: e2e-complex-auto
on: [workflow_dispatch]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # In order for Cypress to run well, it needs to be fed the needed parameters.
    # The below is a mix of Cypress environment variables (All capital) and ones that are needed for this specific set of scripts (Mix of capital and lowercase)
    env:
      CYPRESS_username: ${{ secrets.CYPRESS_USER_NAME }}
      CYPRESS_password: ${{ secrets.CYPRESS_PASSWORD }}
      CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASEURL }}
      CYPRESS_host: ${{ secrets.CYPRESS_HOST }}
      CYPRESS_ENVIRONMENT: ${{ github.base_ref }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Checkout the PR branch
      - name: Checkout Target Branch
        uses: actions/checkout@v3

      # We are cache-ing our node modules to slightly speed up execution in the future.
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list          

      - name: Wait for APP response
        env:
          url: ${{ secrets.CYPRESS_HOST }}
          code: 200
          wait_time: 10
          max_attempts: 5
        run: |
          cd tool-guidance/testing
          chmod +x waitforconnection.sh
          bash ./waitforconnection.sh   

      # This is the actual Cypress action, invoked with a set of extra parameters.
      # Wait-on/wait-on-timeout: This is the Cypress way of waiting for a response from the application under test, but it does not address the API readiness hence the above Waits.
      # record: Switches on recording to the cloud-based Cypress dahsboard
      # install-command: Since we are forcing our libraries (keycloak) to be installed because of version issues, we have to specify "npm ci -f" to install as the normal "npm ci" would results in errors.
      # If you do not run additional libraries or forced the libraries to install, the this option can be left out.
      # working-directory: points to where you test scripts are located
      # browser: Specifies which browser you want to use. The default is 'Electron', but we would typically user 'Chrome' as this represent the majority of our users.
      # ci-build-id: to communicate the PR/Build number to the Cypress Dashboard
      - name: E2E Smoke tests
        uses: cypress-io/github-action@v5
        # let's give this action an ID so we can refer
        # to its output values later
        id: smoke
        continue-on-error: false
        with:
          wait-on: ${{ secrets.CYPRESS_HOST }}
          wait-on-timeout: 120
          record: true
          install-command: npm ci -f
          working-directory: tool-guidance/testing
          browser: chrome
          ci-build-id: ${{ github.event.number }}

      # For review/debug purposes, just print out key parameters
      - name: Print Env Vars
        run: |
          echo Git Base Ref: ${{ github.base_ref }}
          echo Git Change ID: ${{ github.event.number }}
          echo Cypress BaseUrl: $CYPRESS_BASE_URL
          echo Cypress Host: $CYPRESS_HOST
          echo Cypress Environment: $CYPRESS_ENVIRONMENT
