# Workflow starts automatically on push or can be triggered manually.
# This is a desirable pattern as it allows for adhoc test runs without a code push
name: main-e2e
on: [workflow_dispatch, repository_dispatch]
jobs:
  sso-request-tests:
    runs-on: ubuntu-latest
    # In order for Cypress to run well, it needs to be fed the needed parameters.
    # The below is a mix of Cypress environment variables (All capital) and ones that are needed for this specific set of scripts (Mix of capital and lowercase)
    env:
      CYPRESS_username: ${{ secrets.CYPRESS_USER_NAME }}
      CYPRESS_password: ${{ secrets.CYPRESS_PASSWORD }}
      CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASEURL }}
      CYPRESS_host: ${{ secrets.CYPRESS_HOST }}
      CYPRESS_ENVIRONMENT: ${{ github.base_ref }}
      CYPRESS_loginproxy: ${{ secrets.CYPRESS_LOGINPROXY }}
      CYPRESS_siteminder: ${{ secrets.CYPRESS_SITEMINDER }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      USERS: ${{ vars.VAR_USERS }}
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
    steps:
      # Checkout the PR branch
      - name: Checkout Target Branch
        uses: actions/checkout@v3

      # We are cache-ing our node modules to slightly speed up execution in the future.
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: E2E Smoke tests
        uses: cypress-io/github-action@v6.6.0
        # let's give this action an ID so we can refer
        # to its output values later
        id: smoke
        continue-on-error: false
        with:
          summary-title: 'E2E Smoke tests'
          wait-on: ${{ secrets.CYPRESS_HOST }}
          wait-on-timeout: 120
          record: true
          install-command: npm ci --legacy-peer-deps
          working-directory: testing
          spec: |
            cypress/e2e/smoke/smoke-*-*.cy.ts
          browser: chrome
          # project: ./e2e
          ci-build-id: ${{ github.event.number }}

      - name: Request Creation tests
        uses: cypress-io/github-action@v6.6.0
        # let's give this action an ID so we can refer
        # to its output values later
        id: create-request
        continue-on-error: false
        with:
          summary-title: 'Request Creation tests'
          wait-on: ${{ secrets.CYPRESS_HOST }}
          wait-on-timeout: 120
          record: true
          install-command: npm ci --legacy-peer-deps
          working-directory: testing
          spec: |
            cypress/e2e/**/integration-010-*.cy.ts
          browser: chrome
          # project: ./e2e
          ci-build-id: ${{ github.event.number }}

      # Mandatory wait for the background processes to finish
      - name: Sleep for 15 minutes
        uses: jakejarvis/wait-action@master
        with:
          time: '15m'

      - name: Request Validation tests
        uses: cypress-io/github-action@v6.6.0
        # let's give this action an ID so we can refer
        # to its output values later
        id: validation-request
        continue-on-error: false
        with:
          summary-title: 'Request Validation & Roles tests'
          wait-on: ${{ secrets.CYPRESS_HOST }}
          wait-on-timeout: 120
          record: true
          install-command: npm ci --legacy-peer-deps
          working-directory: testing
          spec: |
            cypress/e2e/**/integration-030-*.cy.ts
            cypress/e2e/**/integration-040-*.cy.ts
          browser: chrome
          # project: ./e2e
          ci-build-id: ${{ github.event.number }}

      - name: Request Update tests
        uses: cypress-io/github-action@v6.6.0
        # let's give this action an ID so we can refer
        # to its output values later
        id: update-request
        continue-on-error: false
        with:
          summary-title: 'Request Update tests'
          wait-on: ${{ secrets.CYPRESS_HOST }}
          wait-on-timeout: 120
          record: true
          install-command: npm ci --legacy-peer-deps
          working-directory: testing
          spec: |
            cypress/e2e/**/integration-020-*.cy.ts
          browser: chrome
          # project: ./e2e
          ci-build-id: ${{ github.event.number }}

      # Mandatory wait for the background processes to finish
      - name: Sleep for 10 minutes
        uses: jakejarvis/wait-action@master
        with:
          time: '10m'

      - name: Request Delete tests
        uses: cypress-io/github-action@v6.6.0
        # let's give this action an ID so we can refer
        # to its output values later
        id: delete-request
        continue-on-error: false
        with:
          summary-title: 'Request Deletion tests'
          wait-on: ${{ secrets.CYPRESS_HOST }}
          wait-on-timeout: 120
          record: true
          install-command: npm ci --legacy-peer-deps
          working-directory: testing
          spec: cypress/e2e/**/integration-900-*.cy.ts
          browser: chrome
          # project: ./e2e
          ci-build-id: ${{ github.event.number }}

      - name: Team Tests
        uses: cypress-io/github-action@v6.6.0
        # let's give this action an ID so we can refer
        # to its output values later
        id: teams
        continue-on-error: false
        with:
          summary-title: 'Teams Tests'
          wait-on: ${{ secrets.CYPRESS_HOST }}
          wait-on-timeout: 120
          record: true
          install-command: npm ci --legacy-peer-deps
          working-directory: testing
          spec: |
            cypress/e2e/**/team-*-*.cy.ts
          browser: chrome
          # project: ./e2e
          ci-build-id: ${{ github.event.number }}

      - name: Run the reports
        run: |
          cd testing
          npm run report

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: testing/mochawesome-report
