name: single-test-e2e
on:
  workflow_dispatch:
    inputs:
      filename:
        required: true
        description: 'Name of the cypress test file to run'

jobs:
  sso-request-tests:
    runs-on: ubuntu-latest
    # In order for Cypress to run well, it needs to be fed the needed parameters.
    # The below is a mix of Cypress environment variables (All capital) and ones that are needed for this specific set of scripts (Mix of capital and lowercase)
    env:
      CYPRESS_users: ${{ secrets.CYPRESS_USERS }}
      CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASEURL }}
      CYPRESS_host: ${{ secrets.CYPRESS_HOST }}
      CYPRESS_guid: ${{ secrets.CYPRESS_GUID }}
      CYPRESS_ENVIRONMENT: ${{ github.base_ref }}
      CYPRESS_loginproxy: ${{ secrets.CYPRESS_LOGINPROXY }}
      CYPRESS_siteminder: ${{ secrets.CYPRESS_SITEMINDER }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
    steps:
      # Checkout the PR branch
      - name: Checkout Target Branch
        uses: actions/checkout@v3

      # We are cache-ing our node modules to slightly speed up execution in the future.
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Run test
        uses: cypress-io/github-action@v6.6.0
        id: smoke
        continue-on-error: false
        with:
          summary-title: 'E2E Test'
          wait-on: ${{ secrets.CYPRESS_HOST }}
          wait-on-timeout: 120
          record: true
          install-command: npm ci
          working-directory: testing
          spec: |
            cypress/e2e/**/${{inputs.filename}}
          browser: chrome
          ci-build-id: ${{ github.event.number }}

      - name: Run the reports
        run: |
          cd testing
          npm run report

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: testing/mochawesome-report/report.html
