# Workflow starts automatically on push or can be triggered manually.
# This is a desirable pattern as it allows for adhoc test runs without a code push
name: SSO test
on:
  workflow_dispatch:
    inputs:
      smoketest:
        required: true
        description: 'Is this a smoke test?'
        default: 'false'
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
jobs:
  sso-request-tests:
    runs-on: ubuntu-latest
    # In order for Cypress to run well, it needs to be fed the needed parameters.
    # The below is a mix of Cypress environment variables (All capital) and ones that are needed for this specific set of scripts (Mix of capital and lowercase)
    env:
      CYPRESS_users: ${{ secrets.CYPRESS_USERS }}
      CYPRESS_BASE_URL: 'https://bcgov.github.io/sso-requests-sandbox/'
      CYPRESS_host: 'https://bcgov.github.io/sso-requests-sandbox/'
      CYPRESS_guid: ${{ secrets.CYPRESS_GUID }}
      CYPRESS_ENVIRONMENT: ${{ github.base_ref }}
      CYPRESS_loginproxy: ${{ secrets.CYPRESS_LOGINPROXY }}
      CYPRESS_siteminder: ${{ secrets.CYPRESS_SITEMINDER }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      SERVER_HOST: 'localhost'
      SERVER_PORT: 3000
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
    steps:
      # Checkout the PR branch
      - name: Checkout Target Branch
        uses: actions/checkout@v4

      - name: Checkout SAML Playground
        uses: actions/checkout@v4
        with:
          repository: bcgov/keycloak-example-apps
          path: sso

      # We are cache-ing our node modules to slightly speed up execution in the future.
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Build and Run OIDC Playground
        run: |
          docker run --rm -d -p 3000:3000/tcp playground:latest
        working-directory: ./sso/playground/public-spa

      - name: SSO Test
        uses: cypress-io/github-action@v6
        id: saml
        continue-on-error: false
        with:
          summary-title: 'SSO tests'
          wait-on-timeout: 120
          record: true
          install-command: npm ci
          working-directory: testing
          spec: |
            cypress/e2e/**/sso-010-createIntegration.cy.ts
            cypress/e2e/**/sso-020-sessions.cy.ts
            cypress/e2e/**/integration-990-deleteAllIntegrations.cy.ts
          browser: chrome
          # project: ./e2e
          ci-build-id: ${{ github.event.number }}

      - name: Run the reports
        run: |
          cd testing
          npm run report

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: testing/mochawesome-report/report.html
