on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  test_pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run Pre-Commit
        run: |
          pip install -r requirements.txt
          pre-commit run --color=always --show-diff-on-failure --all-files

  commitlint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5.2.2
